"""cat_charity_fund

Revision ID: 5726e6be90f5
Revises: 6c08fcdfaf4a
Create Date: 2025-11-04 20:49:29.218217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5726e6be90f5'
down_revision = '6c08fcdfaf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
