"""Test2

Revision ID: b6711e8024a3
Revises: b7edf54cf620
Create Date: 2025-11-06 13:56:19.296799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6711e8024a3'
down_revision = 'b7edf54cf620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
