"""Test

Revision ID: b7edf54cf620
Revises: 5726e6be90f5
Create Date: 2025-11-06 13:23:19.461416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7edf54cf620'
down_revision = '5726e6be90f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
